---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: msi-file
  - name: install-script-generator
  - name: diego-release
  - name: cf-release
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/release.rb
params:
  GITHUB_TOKEN:

